### PR TITLE
Use CircularVector instead of CircularSeq for polygon points.

### PR DESCRIPTION
**Pull request by Lemmih**

### CODE REVIEW

**Comment by Lemmih** [comment]
I liked how it turned out. I particularly like how
```
rightMost xs = let m = F.maximumBy (comparing (^.core)) xs in rotateTo' m xs
```
turned into:
```
rightMost = CV.rotateToMaximumBy (comparing (^.core))
```

**Comment by Lemmih** [comment]
If this PR is okay, please squash it instead of creating a merge commit.

**Comment by Lemmih** [comment]
Moving forward with this. Let me know if you want any changes.

**Comment by noinia** [comment]
Looks pretty good to me :)

**Pull request merged**
