### PR TITLE
[WIP] O(nlog n) time algorithm for computing a visibility polygon

### PR DESCRIPTION
**Pull request by noinia**
many details still missing, moreover some types of the functions don't match up yet, but at least the main skeleton is there already.

### CODE REVIEW

**Comment by noinia** [comment]
FYI: I think this works/is complete now, but I should write some proper tests to make sure I didn't make any mistakes.

I also fixed the show/read instances for LineSegment along the way.

**Comment by Lemmih** [comment]
> FYI: I think this works/is complete now, but I should write some proper tests to make sure I didn't make any mistakes.

I have a visibility polygon implementation that uses the SSSP tree. I'll hammer it into shape and submit a PR. Then we can add a QC property that the two algorithms always give the same result.

> I also fixed the show/read instances for LineSegment along the way.

I saw, love it. Good Read/Show instances are worth their weight in gold.

**Comment by Lemmih** [comment]
I pushed a merge commit so remember to pull before making any new changes.

**Comment by noinia** [comment]
> > FYI: I think this works/is complete now, but I should write some proper tests to make sure I didn't make any mistakes.
> 
> I have a visibility polygon implementation that uses the SSSP tree. I'll hammer it into shape and submit a PR. Then we can add a QC property that the two algorithms always give the same result.

Ah nice, that seems useful. 

One thing to maybe think a bit about is how we treat "spikes", something like this:
image
on the rightmost edge there is a single point that could be considered visible. My current implementation does not include such spikes in the visibility polygon.

**Comment by noinia** [comment]
Fixing some weird degeneracy issues (like the one shown above) lead me down some wild goose chase into computing intersections between points and segments, and points and halflines. In particular, I realized that in 2D we can test if a point lies on a linesegment by using only 3 ccw tests. I'm guessing that that will be more robust (and potentially faster) than the generic onSegment test we were using so far. I'm hoping that this may also fix some of the issues users reported that were using Doubles as their numeric type.

**Comment by Lemmih** [comment]
Is this PR done? Done enough to be merged?

**Comment by noinia** [comment]
Seems there is still some bug that I need to fix before we merge this.

**Comment by Lemmih** [comment]
What bugs? Anything I can help with? There are so many goodies in this PR that I would like to see merged.

**Comment by noinia** [comment]
I finally had some time to make some progress on this. Seems like its mostly doing the right thing now. I'm hoping to actually wrap this up tomorrow so that we can also release 0.12 soon :)

**Pull request merged**
