### PR TITLE
SSSP

### PR DESCRIPTION
**Pull request by Lemmih**
- [x] Naive O(n^3) implementation.
 - [x] O(n) implementation (using a fingertree).
 - [x] Better Read/Show instance for Point and SomePolygon. This made testing a lot easier.

With a better way of computing visibility polygons, the naive implementation could run in O(n^3).

Current problems:
 - ~~The implementation assumes O(1) access to polygon vertices.~~
 - ~~The outer face is assumed to be `FaceId 0`.~~
 - There's no way to select which vertex to use as the source.

### CODE REVIEW

**Comment by Lemmih** [comment]
If we merge #53 then it would be easier to create a `TriangulatedPolygon` type. It could store the plane graph using absolute offsets to identify the points in the polygon. Then we could have `O(1)` rotate without the graph and polygon getting out of sync.

**Comment by noinia** [comment]
Cool! 

Is there a reason for using FloydWarshall rather than dijkstra to compute the shortest paths? The visibility graph has O(n) vertices and O(n^2) edges, so computing a single shortest path three should just take O(n^2 log n) time no?  Maybe that is somewhat moot for simple polygons (since we have the linear time implementation), but for polygons with holes O(n^2 log n) using the visibility graph should be doable. (Note that there computing the SPM then still requires some more work but still).

**Comment by Lemmih** [comment]
FloydWarshall was the simplest solution that would be obviously correct. My only goal was a baseline against which to compare the linear implementation.

Visibility algorithms that work with holes would be nice. We'd need something like this:
 1. Vertex visibility in `O(n log n)`. Which would give a visibility graph in `O(n^2 log n)`. The BentleyOttmann code can be adapted to do this, right?
 2. An implementation of Dijkstra's algorithm. Can we borrow an implementation that has already been written?

Looks like there's an `O(n log n)` algorithm[1] as well. Sounds like it would fit well in hgeometry. I'm somewhat confused about these algorithms, though:
 1. [New methods for constructing visibility graphs](https://dl.acm.org/doi/10.1145/73393.73410)
 2. [An output sensitive algorithm for computing visibility graphs](https://www.cs.umd.edu/~mount/Papers/sicomp91-visib.pdf)
 2. [Topologically sweeping visibility complexes via pseudotriangulations](https://link.springer.com/article/10.1007/BF02712876)
 3. [Efficiently Constructing the Visibility Graph of a Simple Polygon w/ obstacles](http://dl.acm.org/citation.cfm?id=586969)

They seem very situational. Would it be worthwhile to have them in hgeometry? I have no formal training in computational geometry and it's really difficult for me to see which algorithms are significant and which aren't.

[1]: http://citeseerx.ist.psu.edu/viewdoc/summary?doi=10.1.1.47.2037&rank=2

**Comment by Lemmih** [comment]
Oh, btw, to get exact results with FloydWarshall or Dijkstra's algorithm, we need a way to compare sums of square roots. Do you know how to do this or can you recommend a paper? @noinia

**Comment by noinia** [comment]
> FloydWarshall was the simplest solution that would be obviously correct. My only goal was a baseline against which to compare the linear implementation.

Fair enough :). 

> Visibility algorithms that work with holes would be nice. We'd need something like this:
> 
>     1. Vertex visibility in `O(n log n)`. Which would give a visibility graph in `O(n^2 log n)`. The BentleyOttmann code can be adapted to do this, right?

We can use the visibility polygon algorithm that I wrote/am writing to this end: for each vertex v we compute the visibility polygon, for each vertex u in the visibility polygon that is also a vertex of P, we get an edge (v,u) in the visibility graph. (and all other vertices of P are invisible from v, and thus do not get an edge).  This way we can compute the visibility graph in O(n^2 log n) time.

>     2. An implementation of Dijkstra's algorithm. Can we borrow an implementation that has already been written?

A quick hackage search shows that there are some implementations. E.g.

- https://hackage.haskell.org/package/dijkstra-simple-0.1.0/docs/Graph-DijkstraSimple.html
- https://hackage.haskell.org/package/search-algorithms-0.3.1/docs/Algorithm-Search.html#v:dijkstra

Unfortunately, they don't specify what type of priority queue they are using (and thus what their running time is). I'm guessing they will run in O((V+E) log V) time. (Which is good enough at this point, but still). 

> Looks like there's an `O(n log n)` algorithm[1](http://citeseerx.ist.psu.edu/viewdoc/summary?doi=10.1.1.47.2037&rank=2) as well. Sounds like it would fit well in hgeometry. I'm somewhat confused about these algorithms, though:
> 
>     1. [New methods for constructing visibility graphs](https://dl.acm.org/doi/10.1145/73393.73410)
> 
>     2. [An output sensitive algorithm for computing visibility graphs](https://www.cs.umd.edu/~mount/Papers/sicomp91-visib.pdf)
> 
>     3. [Topologically sweeping visibility complexes via pseudotriangulations](https://link.springer.com/article/10.1007/BF02712876)
> 
>     4. [Efficiently Constructing the Visibility Graph of a Simple Polygon w/ obstacles](http://dl.acm.org/citation.cfm?id=586969)
> 
> 
> They seem very situational. Would it be worthwhile to have them in hgeometry? I have no formal training in computational geometry and it's really difficult for me to see which algorithms are significant and which aren't.

I think all these algorithms are interesting, but I'm not sure how much time we would want to invest in this particular problem. I.e. 1 and 3 present O(n^2) time algorithms, 2 and 4 give something like O(n log n + E). In terms or running time, 1 and 3 thus only allow us to shave a log factor. Out of those two, 1 is most interesting (since it essentially solves a more general problem: cyclically sorting the points). For this to be useful for the shortest path problem we would then also need a "proper" dijkstra implementation that runs in O(Vlog V + E) time (so we need some Fibbonoacci Heap or Hollow heap).

The latter two algorithms are interesting if the visibility graph itself is small (i.e. every vertex does not see too many other vertices), but they are also more complicated to implement. Since the "simple" method above runs in O(n^2 log n) time, I'm not sure the additional effort is worth it at this point. (But of course if you think this is interesting, feel free to implement the algorithms; I would be happy to add them to hgeometry).

> Oh, btw, to get exact results with FloydWarshall or Dijkstra's algorithm, we need a way to compare sums of square roots. Do you know how to do this or can you recommend a paper? @noinia

Unfortunately that is an open problem :(. See [the TOPP Project][https://topp.openproblem.net/p33] for details if you are interested.

**Comment by Lemmih** [comment]
> > Oh, btw, to get exact results with FloydWarshall or Dijkstra's algorithm, we need a way to compare sums of square roots. Do you know how to do this or can you recommend a paper? @noinia
> 
> Unfortunately that is an open problem :(. See [the TOPP Project](https://topp.openproblem.net/p33) for details if you are interested.

Ah, that's a shame.

What are your thoughts on this paper: [An Optimal Algorithm for Euclidean Shortest Paths in the Plane](http://citeseerx.ist.psu.edu/viewdoc/summary?doi=10.1.1.47.2037&rank=2)? Is it the fastest way to compute the shortest paths in the presence of obstacles? It would be nice to have something better than `O(n^2)`.

Happy holidays, btw. :)

**Comment by Lemmih** [comment]
The SSSP code still doesn't support selecting an arbitrary source vertex without having to re-triangulate the polygon. But I'd like to add that to another PR and get this one merged.

**Comment by noinia** [comment]
> > > Oh, btw, to get exact results with FloydWarshall or Dijkstra's algorithm, we need a way to compare sums of square roots. Do you know how to do this or can you recommend a paper? @noinia
> > 
> > 
> > Unfortunately that is an open problem :(. See [the TOPP Project](https://topp.openproblem.net/p33) for details if you are interested.
> 
> Ah, that's a shame.
> 
> What are your thoughts on this paper: [An Optimal Algorithm for Euclidean Shortest Paths in the Plane](http://citeseerx.ist.psu.edu/viewdoc/summary?doi=10.1.1.47.2037&rank=2)? Is it the fastest way to compute the shortest paths in the presence of obstacles? It would be nice to have something better than `O(n^2)`.
> 
> Happy holidays, btw. :)

Happy Holidays! 

That is a wonderful paper, and the only known algorithm to compute a SPM (or even a single shortest path) in O(n log n) time. It would be seriously awesome to have that in HGeometry. That would probably require some significant amount of work though, it requires building a particular type of subdivision, and then some wavefront propagation through this subdivision. Especially the second part is pretty finicky I think. One of the authors of that paper (John Hershberger) did tell me a while ago he/they found that some parts could be somewhat simplified. I don't think those simplifications have been published anywhere. The main point was that their writeup describes how to computes the exact subdivision of the polygon s.t. all points in a region have a single, unique shortest path. For computing the shortest path from some query point q it is sufficient if the data structure allows you to find O(1) candidate paths, and just pick the actual shortest one at query time. That would make the data structure slightly simpler.

Awesome work on the SSSP algorithm for in simple polygons by the way :)

**Pull request merged**
